# Generated by Django 4.0.2 on 2024-01-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltable',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
