# Generated by Django 4.0.2 on 2024-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_urltable_report_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.CharField(blank=True, max_length=255, null=True)),
                ('locname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gp_loc',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='urltable',
            options={'managed': False},
        ),
    ]
