# Generated by Django 4.0.2 on 2024-01-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gploc_alter_urltable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('Report', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='urltable',
            options={},
        ),
    ]
