# Generated by Django 4.0.2 on 2024-01-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_report_alter_urltable_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Report',
            new_name='report',
        ),
        migrations.AddField(
            model_name='urltable',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.report'),
        ),
    ]
