# Generated by Django 4.0.2 on 2024-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_report_report_report_err_report_err_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltable',
            name='lad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
