# Generated by Django 4.0.2 on 2024-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_urltable_lad'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
